<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>

<div class="block-content">
	<form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
		<div class="field search">
			<div class="control">
				<input id="search"
				   data-mage-init='{"quickSearch":{
						"formSelector":"#search_mini_form",
						"url":"<?= /* @escapeNotVerified */ $helper->getSuggestUrl()?>",
						"destinationSelector":"#search_autocomplete"}
				   }'
				   type="text"
				   name="<?= /* @escapeNotVerified */ $helper->getQueryParamName() ?>"
				   value="<?= /* @escapeNotVerified */ $helper->getEscapedQueryText() ?>"
				   placeholder="<?= /* @escapeNotVerified */ __('Enter keywords to search...') ?>"
				   class="input-text"
				   maxlength="<?= /* @escapeNotVerified */ $helper->getMaxQueryLength() ?>"
				   role="combobox"
				   aria-haspopup="false"
				   aria-autocomplete="both"
				   autocomplete="off"/>
				<div id="search_autocomplete" class="search-autocomplete"></div>
				<?php echo $block->getChildHtml() ?>
			</div>
		</div>
		<div class="actions">
			<button type="submit" title="<?php echo $block->escapeHtml(__('Search')) ?>"  class="btn-search-header">
				<span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
			</button>
		</div>
	</form>
</div>
