<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
 
$_config = $this->helper('Sm\Maximum\Helper\Data');
$footerStyle = $_config->getThemeLayout('footer_style');
?>

<?php if($_config->getAdvanced('show_gototop')){ ?>
	<a id="yt-totop-fix" href="javascript:void(0)" title="Go to Top"></a>
<?php } ?>

<?php if($footerStyle == "footer-1"){ ?>
	<div class="footer-container footer-style-1">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-1-content')->toHtml(); ?>
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-social-content')->toHtml(); ?>

        <div class="footer-bottom">
            <div class="container">
				<?php if($_config->getAdvanced('custom_copyright')){ ?>
					<address><?php echo $_config->getAdvanced('copyright_content') ?></address>
				<?php } else {?>
					<address><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></address>
				<?php } ?>
            </div>
        </div>
	</div>
<?php } ?>
