<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Catalog\Block\Product\AbstractProduct */

$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();        
$storeManager  = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeID       = $storeManager->getStore()->getStoreId(); 
if($storeID == 16)
{
$_product = $block->getProduct(); 
 $dmeValue=  $_product->getResource()->getAttribute('dme')->getFrontend()->getValue($_product); 
 $dmelabel=$_product->getResource()->getAttribute('dme')->getStoreLabel();
 if ($dmeValue != '' ){

  echo $dmeValue."<br>"; 

}
}
?>
<?= $block->getReviewsSummaryHtml($block->getProduct(), false, true) ?>
