<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\AuthorizationLink $block */

$dataPostParam = '';
/*if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}*/
$helper = $this->helper('\Magento\Checkout\Helper\Cart');
$totalQuantity=$helper->getItemsCount();?>
<li><a href="/baby-einstein-take-along-tunes-musical-toy.html">First Month Free! </a></li>
<li><a href="/checkout/cart/">Cart</a></li>
<li><a href="/customer/account/">My Account</a></li>
<li><a href="/contact-us">Contact Us</a></li>
